# Generated by Django 5.0.7 on 2024-08-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='num_of_listens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
