# Generated by Django 5.0.7 on 2024-08-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_song_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='num_of_listens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Publish')], default='pb', max_length=5),
        ),
        migrations.AddField(
            model_name='artist',
            name='num_of_listens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Publish')], default='pb', max_length=5),
        ),
    ]
