# Generated by Django 5.0.7 on 2024-08-15 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_album_num_of_listens_album_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='num_of_listens',
            new_name='profile_views',
        ),
    ]
